[language-server.biome]
command = "./node_modules/@biomejs/biome/node_modules/.bin/biome.CMD"
args = ["lsp-proxy"]

[language-server.efm-lsp-biome]
command = "efm-langserver"

[language-server.efm-lsp-biome.config]
documentFormatting = true
languages = { typescriptreact = [
  { formatCommand = "pnpm biome check --write -unsafe --stdin-file-path=${INPUT}", formatStdin = true },
], typescript = [
  { formatCommand = "pnpm biome check --write -unsafe --stdin-file-path=${INPUT}", formatStdin = true },
], javascript = [
  { formatCommand = "pnpm biome check --write -unsafe --stdin-file-path=${INPUT}", formatStdin = true },
] }

[[language]]
name = "tsx"
language-servers = [
  "typos",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "tailwindcss-ls",
  "vscode-eslint-language-server",
  { name = "efm-lsp-biome", only-features = [
    "format",
  ] },
  { name = "biome", except-features = [
    "format",
  ] },
  "emmet-ls",
]
auto-format = true

[[language]]
name = "typescript"
language-servers = [
  "typos",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "tailwindcss-ls",
  "vscode-eslint-language-server",
  { name = "efm-lsp-biome", only-features = [
    "format",
  ] },
  { name = "biome", except-features = [
    "format",
  ] },
  "emmet-ls",
]
auto-format = true

[[language]]
name = "jsx"
language-servers = [
  "typos",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "tailwindcss-ls",
  "vscode-eslint-language-server",
  { name = "efm-lsp-biome", only-features = [
    "format",
  ] },
  { name = "biome", except-features = [
    "format",
  ] },
  "emmet-ls",
]
auto-format = true

[[language]]
name = "javascript"
language-servers = [
  "typos",
  { name = "typescript-language-server", except-features = [
    "format",
  ] },
  "tailwindcss-ls",
  "vscode-eslint-language-server",
  { name = "efm-lsp-biome", only-features = [
    "format",
  ] },
  { name = "biome", except-features = [
    "format",
  ] },
  "emmet-ls",
]
auto-format = true
